### ISSUE TITLE
FR: Add materialdesignicons to MainUI

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-webui#1081]
I was looking for some automative icons for the new carnet widget and found some at 
https://dev.materialdesignicons.com

Would it be possible to add those ?

Instructions for VueJS can be found here :
https://dev.materialdesignicons.com/getting-started/vuejs

**Comment by ghys** [comment]
The above https://dev.materialdesignicons.com/getting-started/vuejs refers to cases where the icon to use is known in advance and not dynamic. So in case of widgets where it needs to be user-configurable the implementation options would be:

- use the webfont but it's rightly discouraged because it's really large (https://dev.materialdesignicons.com/guide/webfont-alternatives), 292 KB + the CSS, compare to 108 KB for the f7 icons and 81 KB for the material icons. This would mean half a MB of icon webfonts only, which is quite a lot;
- find a way to lazy load them (with webpack or by putting the SVG files in a static folder)
- I've investigated how Home Assistant deals with them; apparently they load them into a local IndexedDB database as a cache and then retrieve them from there, this could be a good idea to copy
![image](https://user-images.githubusercontent.com/2004147/121860394-153a5700-ccf9-11eb-8413-00b922dc2ab3.png)

**Comment by hmerk** [comment]
Thanks Yannick for looking into this.
Let‘s close it for now then.

**Comment by digitaldan** [comment]
Actually, those icons look pretty great, there are a lot common IoT controlled "things"  there that are not in our other icon sets.

**Comment by ghys** [comment]
> Actually, those icons look pretty great, there are a lot common IoT controlled "things" there that are not in our other icon sets.
Yes see for instance the list here https://dev.materialdesignicons.com/guide/home-assistant#common-home-based-icons

I never said they won't ever be added as a built-in set, so I'll reopen.

Just know their source are the SVG here: https://github.com/Templarian/MaterialDesign/tree/master/svg
So at least for now you can always clone the repo and use the standard OH feature and copy the ones you need to `conf/icons/classic` and then they will be available (in black, to make them white or change the color you'll have to use CSS filters).
If there are hyphens in the name, you'll need to add one as a suffix or part of the name will be interpreted as the state. You can check all of this out in the developer tools, Debug tab.

![image](https://user-images.githubusercontent.com/2004147/121941381-7bea5f80-cd4f-11eb-8986-86ff4f9da59b.png)

(note the last `-`)

**Comment by hmerk** [comment]
@ghys Thanks for reopening and still considering those icons.
I already use a couple of SVG's from this repo for my carnet widget, but have to provide adopted versions for different colors. So I thought it might be easier to have them integrated generally.
