### ISSUE TITLE
Item name not visible in mobile view

### ISSUE THREAD

**Issue by arins** [openhab/openhab-webui#1191]
Is it possible to put the item name on a new line and make the text smaller for mobile view? It is easier to see what the rule is doing in mobile view. See the image below. I can see the what the rule is doing but not to which items the action is performed on.

![Screenshot_20211031-092341_Chrome](https://user-images.githubusercontent.com/1004420/139574439-53f7dd16-1107-400b-aea0-2b34f8f4b2de.jpg)

**Comment by florian-h05** [comment]
If you rotate your phone and use landscape mode instead, you can see the whole texts.
I’ve just checked this.

I also guess that it’s a minority of users that edit rules via their mobile phones, because of the small screens. I usually use my iPad or my desktop system, but nearly never use my phone.


Therefore, the effort to support this is not related to impact it has to amount of users who would profit from that, hence, I hope you don't mind that I close this one.
