### ISSUE TITLE
Reverse proxy with authentication though redirection not working with service worker

### ISSUE THREAD

**Issue by tarag** [openhab/openhab-webui#1207]
## The problem

MainUI does not work behind a reverse proxy performing authentication through redirection (not Basic Auth). When the user tries to access openHAB landing page, if not authenticated but if the service worker has been previously cached, there is no redirection to the authentication page as it is the API call that are redirected and fail.

When authenticated, the setup works flawlessly (and in fact much better than Basic Auth where some browser may repeatedly ask for credentials).

## Expected behavior

In case of redirection of an API call, the entire browser window should be reloaded to the current URL, providing an opportunity for the browser to follow the redirection to the external authentication page.

As suggested in this other issue  #1018, a configuration option to disable service worker could also be a solution.

## Steps to reproduce

1. Install and configure reverse proxy with authentication through redirection
2. Log in with reverse proxy
3. Access openHAB page
4. Log out from reverse proxy
5. Refresh openHAB page

## Your environment

openHAB stable 3.1.0
Web UI in browser (desktop: Safari 14, Chrome 94, mobile Safari 14)
nginx SSL reverse proxy with [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) module
[vouch-proxy](https://github.com/vouch/vouch-proxy) authentication proxy

## Browser console

Example error message when displaying openHAB from service worker cache.

```txt
[Error] XMLHttpRequest cannot load https://REDACTED.auth0.com/authorize?client_id=REDACTED&redirect_uri=https%3A%2F%2FREDACTED_OH_HTTP_NAME%2Fsso%2Fauth&response_type=code&scope=openid+email+profile&state=6F9uv2BorAr86SRC5Gc8oc3GrZBsIBZ due to access control checks.
```

## Browser network traffic

<img width="1254" alt="Screenshot 2021-11-15 at 17 31 56" src="https://user-images.githubusercontent.com/11686092/141819684-81edd242-cfa4-4024-9781-fde6e1194b21.png">

<img width="1203" alt="Screenshot 2021-11-15 at 17 32 45" src="https://user-images.githubusercontent.com/11686092/141819522-5b4677f4-fb3f-4462-a71c-1543b2fa2c15.png">

## Additional information

None

**Comment by ghys** [comment]
This is only partly a service worker problem (it is only used for caching resources atm), but it's true that the first XHR request made by the UI when it loads is a call to `/rest/` to retrieve & store the runtime info and which API endpoints are available.

With the current implementation this request isn't supposed to fail because it isn't subject to authorization at the OH level and, if you're using a proxy with Basic auth or cookie-based auth, you'd have authenticated already.

In your case it appears this `/rest/` request responds with a 302 (redirect), which could perhaps be caught so the browser would navigate to the login page.

So either we would need to:
1) deal with these situations (i.e. the UI has loaded from the service worker cache but can't call the API because it hasn't been authorized yet), maybe by figuring out the API request is being redirected and figure out the  login page from the Location response header
2) tweak the caching mechanism so that the initial page (index.html) wouldn't be put in the cache and therefore would be fetched every time and therefore follow the eventual redirects. This, however, would probably disqualify the UI from the "PWA" status, and therefore browsers would not offer prompts to "add it to the home page" or similar.

**Comment by tarag** [comment]
Thanks for your analysis. The issue doesn’t happens in the nominal initial login flow. It happens in other situations that are still quite common : manually entering openHAB server url in the browser address bar and loading from cache or logging out of the external authentication system on another page or due to expiration and having the openHAB web UI silently fail to refresh. 

I think not caching the index.html page  (your first proposal) would not be enough to handle the second situation. 

I understand that your second proposal would be handling a redirect in a dedicated pop up iframe so that the user could enter his credentials ? I think it could be enough to cover both cases. 

Do you have some pointer on where to start?  I could try to implement this.

**Comment by ghys** [comment]
> With the current implementation this request isn't supposed to fail because it isn't subject to authorization at the OH level and, if you're using a proxy with Basic auth or cookie-based auth, you'd have authenticated already.

This assessment wasn't quite correct, in fact there's a whole bunch of code to handle situations where the `/rest/` call doesn't succeed even if the UI has been loaded (from the service worker cache).

https://github.com/openhab/openhab-webui/blob/1e916dad8add25ac876d259f8ff12fd4ba713db9/bundles/org.openhab.ui/web/src/components/app.vue#L378-L411

It's assumed that receiving a 401 (or Unauthorized) error here means there are Basic auth credentials to send - because it's the most common scenario, in particular home.myopenhab.org or openHAB Cloud instances in general.

In your case though I don't believe you fall in the `err === 'Unauthorized' || err === 401` case so the method just returns with a rejected promise. Maybe try to add a debugger breakpoint on line 380 above to check what `err` is.

There are a few critical places where the promise result isn't checked (no `catch()`) so that's probably why the UI simply doesn't load when `loadData()` ends up rejected.
I'm not the biggest fan of the iframe trick but wondering if there would be other cleaner techniques to force a redirect - perhaps adding a parameter like `window.location = '?reload'` or similar...

**Comment by florian-h05** [comment]
@ghys Can you please assign me to this issue?
