### ISSUE TITLE
[MainUI] Translated binding name ignored in the bindings page

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#1213]
I would expect the display of "Extension Astro" rather than "Astro Binding" for example in the bindings/marketplace page because "Extension Astro" is the French translation for this binding name.

![image](https://user-images.githubusercontent.com/10186704/143675647-52572b6e-44e3-427f-83d9-3b348a8ea3fc.png)

**Comment by clinique** [comment]
Isn't this because it's based on factures.xml file instead of binding.xml ?

**Comment by lolodomo** [comment]
Why is it tagged as invalid? 
My screen capture is clear, no? 
If translation was working, I should "Extension Astro".

**Comment by wborn** [comment]
It's more an OHC issue because the REST API currently cannot return localized add-on names. The reason is that all the localization strings in bundles are unavailable until you install the bundle using the feature. :wink:  When this is solved in OHC, it should probably work without any changes in the UI.

**Comment by ghys** [comment]
Yes, the tag is how I move issues that have clearly nothing to do with the UI itself out of my main filter...

More generally a lot of inconsistencies may also have to do with the browser configuration, since the API tends to consider that the `Accept-Language` header trumps the `org.openhab.i18n` service configuration.

If you have the browser configured like this

![image](https://user-images.githubusercontent.com/2004147/146648612-c70b8aed-bcc9-476f-acdc-891d31bc5689.png)

Then you'd have many API responses in English even if openHAB is configured in French, because requests have a:
`Accept-Language: en-US,en;q=0.9,de;q=0.8,fr-FR;q=0.7,fr;q=0.6`
header sent by the browser.

I think I mentioned it before, but I think the `Accept-Language` header should be ignored if a language is set server-wide, if not at all (become some other things will not consider it anyways, and rely on the server config only; for instance, the login/authorize/change password screens).

**Comment by lolodomo** [comment]
Ok. But in the current case, the bindings are already installed.

**Comment by wborn** [comment]
It would be a confusing UX when add-on names change whenever you (un)install add-ons. :upside_down_face:

**Comment by lolodomo** [comment]
I can just confirm that my browser (Firefox) is setup for French:
![image](https://user-images.githubusercontent.com/10186704/146652221-acc03405-655c-4d83-bb13-c3e50639eb07.png)

I also tried with Chrome and Edge and same result.

**Comment by ghys** [comment]
It's actually the settings for pages not menus that is important

![image](https://user-images.githubusercontent.com/2004147/146652486-1a1d163f-e8a1-466a-9b3b-06cae29b4089.png)

![image](https://user-images.githubusercontent.com/2004147/146652497-12824b2f-6518-43d0-b7ea-408f7c25399a.png)

![image](https://user-images.githubusercontent.com/2004147/146652511-5aa0c2f7-6b08-4b5c-ba26-ad1ca5c001ad.png)

![image](https://user-images.githubusercontent.com/2004147/146652519-f5bf729a-9ac8-4c14-bfd4-78622cb6b5f6.png)

The add-on store (and the `/rest/addons` endpoint) is different and doesn't offer translations in any case.

**Comment by lolodomo** [comment]
In Firefox, I see only one place to setup the language.

Note that in another MainUI place (adding new thing), I see correct translations:
![image](https://user-images.githubusercontent.com/10186704/146672757-95b3f3d6-a7f1-428a-a7a4-f23bc97c9758.png)

**Comment by lolodomo** [comment]
If I use the API Explorer, I got this, that is no translation:
![image](https://user-images.githubusercontent.com/10186704/146672923-073f60f6-7322-49f8-97b8-c851847c2afd.png)

Same result if I add "fr-FR" as accept-language header.

**Comment by wborn** [comment]
That UI page probably uses the `/rest/bindings` endpoint.

**Comment by lolodomo** [comment]
I do not remember if this is was correctly translated before the marketplace stuff was added.

**Comment by lolodomo** [comment]
> That UI page probably uses the `/rest/bindings` endpoint.

Oh yes, the bindings REST API is working well, you're right.
So that means it is possible to return translated label/description in the addons API too ?

**Comment by wborn** [comment]
Yes but the main issue still is that the /addons endpoint is based on Karaf features and you cannot access translations of bundles that haven't been installed.

So it would help if the add-on/feature metadata (https://github.com/openhab/openhab-core/issues/2058) is aggregated and is available without having to install all add-ons. :slightly_smiling_face:

**Comment by lolodomo** [comment]
> Yes but the main issue still is that the /addons endpoint is based on Karaf features and you cannot access translations of bundles that haven't been installed.

But for the ones that are already installed ?

**Comment by wborn** [comment]
Then I agree with @wborn  in https://github.com/openhab/openhab-webui/issues/1213#issuecomment-997230256

> It would be a confusing UX when add-on names change whenever you (un)install add-ons. :upside_down_face:

**Comment by ghys** [comment]
> Then I agree with @wborn in #1213 (comment)

That is reassuring 🤣

**Comment by lolodomo** [comment]
Closed as (partially) resolved.
