### ISSUE TITLE
Cannot link Temperature:Number channel to Temperature:Number Group item

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-webui#1477]
## The problem

When trying to link Temperature:Number channel to an item, the group item with the same "sub type".

MainUI is not even showing the group item in the list of items and thus, linking cannot be done.

I believe the issue is there for all item types, not just Number:Temperature.

## Expected behavior

Group items can be linked to.

## Steps to reproduce

1. 

## Your environment

```yaml

```

## Browser console

```txt

```

**Comment by ssalonen** [comment]
I presume this is a valid channel-item link? If not, I stand corrected.

**Comment by rkoshak** [comment]
I don't think it's valid to link a Channel to a Group Item. This has been explored quite a bit on the forum but I do notice that it's not explicitly stated in the docs.

The problem is what does it even mean to link to a Group? The Group's state is supposed to represent an aggregation of all the states of its members (if it has a state at all). What would it mean for a Group to have its own state independent of its members? What if it has an aggregation function and a Link, which one supplies the state?

**Comment by ssalonen** [comment]
Right, that makes sense.

In my context I am only interested in having the channel link for _commands_, not state. Nevertheless, dilemma you highlighted still exists, especially when considering `autoupdate` and other details.

Closing the ticket.
