### ISSUE TITLE
MainUI can't control setpoint items (for example target temperature)

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-webui#1494]
Unfortuantely MainUI can still not control setpoint items like the target temperature of a thermostat. A readOnly=false configured setpoint item is just displayed with an "Analyze" button and a read-only graph is opened with a click on it. That is completely useless. Instead there should for example be a slider widget.

This affects a lot of the bindings. A fix would be great to increase the usability of MainUI.

See also https://github.com/openhab/openhab-webui/issues/765#issuecomment-886258778

OpenHAB 3.3.0 is also affected.

**Comment by Novanic** [comment]
Hello @ghys , could you please re-open the issue? It isn't fixed within OpenHAB 3.4...

**Comment by ghys** [comment]
Can you provide any details? Is the item you're using as a setpoint tagged "Setpoint" (or "Control")?
It's a requirement if you want a stepper or slider by default: see https://github.com/openhab/openhab-webui/pull/1558#issuecomment-1345574684.
Binding authors should also add the appropriate tags to the channel type definitions so they are added when the link is created in the UI.

**Comment by mkrathome** [comment]
> Can you provide any details? Is the item you're using as a setpoint tagged "Setpoint" (or "Control")?
It's a requirement if you want a stepper or slider by default: see #1558 (comment).
Binding authors should also add the appropriate tags to the channel type definitions so they are added when the link is created in the UI.

Hi,
@ghys I'm not quite sure, if @Novanic opens this after I got in struggle with creating sitemap out  of sematic model. I can not say, if it is solved for all the fancy UI stuff, because I'm only use sitemap. But I recognize, that now stepper-card is added at item configuration.

The issue raised up in the livisi-community and we found out, that also the UI-default-Widgets are not useful.

My problem is not solved: if I rebuild my home at semantic model and put some thermostate-equippment as group in a room, and add this group to the sitemap, I have no chance to change the target temperature. I tried many things: item types and all kind of metadata defining the only thing I get to run is a list-widget. 

For me the idea was to modelling the whole system and only but the top level in the sitemap.  I thought, that should be the way to get the System as simple as possible also for not engineers.

Hope you agree and can fix that 

All the Best  Manuel
