### ISSUE TITLE
[blockly] Add "Get Time from DateTime Item" option

### ISSUE THREAD

**Issue by Gifford47** [openhab/openhab-webui#1636]
## The problem

To extract a time from a datetime item, I had to add several blocks to get my desired formatting. A new option in the existing DateTime blocks would be nicer.
![image](https://user-images.githubusercontent.com/49484063/212025092-96a66f2a-6036-4773-88c7-7fb30dc1ad48.png)

## Your suggestion

An option like "Custom" in the DateTime blocks would be handy:
![image](https://user-images.githubusercontent.com/49484063/212025458-0ae3dc0b-2c1e-418f-b9ad-7169bd4053fc.png)

## Your environment

OH 3.4.1

```yaml

```

**Comment by stefan-hoehn** [comment]
The proposal I did here https://community.openhab.org/t/blockly-aktuellezeit-als-ss-mm/143110/6

is as follows

![image](https://user-images.githubusercontent.com/5937600/212476695-08c37fa6-53e7-4180-94f7-954f08404720.png)

Would that suit your needs?

**Comment by Gifford47** [comment]
Yes, thanks!
That's exactly what I want.
Could you send the code block for a new blockly lib for me?

**Comment by stefan-hoehn** [comment]
The code will be a bit more complicated at it seems at first sight in the implementation of the core blocks because it involves a "mutator" that changes the block design when you change to "with pattern" because it will dynamically add the pattern input field in that case. This behaviour cannot be achieved with a block library, afaik. If you want to know how you can still achieve the same, look at the provided thread link above as a workaround for the time being.

**Comment by stefan-hoehn** [comment]
@openhab/webui-maintainers is there a way I can assign myself to this issue?
