### ISSUE TITLE
Add a round slider

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-webui#1640]
While the existing knob is not what I really like for widget creation, I would rather like to have something like this
https://vue.roundsliderui.com/

@ghys Any chance to have this implemented ?

**Comment by ghys** [comment]
Probably not as a separate widget as it's rather redundant, like you said the oh-knob already supports something like this.
A setting in oh-knob which would switch implementations (using either vue-knob-control or vue-round-slider), why not.

**Comment by hmerk** [comment]
Thanks for your feedback Yannick.
Could you put this on your todo list, as I am absolut not familiar with those VUE/GUI stuff.
Thanks.

**Comment by stefan-hoehn** [comment]
Hi Hans-Jörg (@hmerk ) , I have put it onto my todo list and started working on it (@ghys Can you assign the ticket to me?).

I have come pretty far already as you can see below. I should be able to provide a PR pretty soon.

There is a button that allows to switch between the types. The standard properties are compatible and I already added two more properties that would only work with the rounded slider, which is start angle and end angle. I added them to the advanced properties (I will add some info to the description that this only works with the rounded slider). I am not sure if there is a way only to allow these to edit dynamically under the circumstance of that type.

https://user-images.githubusercontent.com/5937600/217481549-a757c3ce-2f31-4886-9036-aa10ee27e154.mov

I hope you like that? 😊

**Comment by hmerk** [comment]
@stefan-hoehn Of course I like it, whit will bring some of our widgets to the next level of ;-)
I will check later on and give you some feedback on what I would like to have implemented.

**Comment by hmerk** [comment]
Ok, just a quick wishlist:
- borderWidth
- borderColor
- circleShape

I would like to build something like the following :
Picture 3 and 4 from
https://github.com/soundar24/vue-round-slider/raw/master/assets/different-appearances.png

**Comment by stefan-hoehn** [comment]
I added several attributes

**borderWidth:**

<img width="360" alt="image" src="https://user-images.githubusercontent.com/5937600/217810115-df344d0c-661b-4f7d-81d4-b6f677759670.png">

**borderColor**

<img width="123" alt="image" src="https://user-images.githubusercontent.com/5937600/217810455-e9cbeb6b-559e-4a03-af24-8d725162aca1.png">

**circle shape** (full, pie, half-top/-bottom/-left/-right, quarter-top-left/-right, quarter-botton-left/right)

_Pie:_

<img width="123" alt="image" src="https://user-images.githubusercontent.com/5937600/217811181-4d9b9c74-78a5-4ab0-bb3b-8fa528adcd65.png">

_Pie with start angle -45_

<img width="125" alt="image" src="https://user-images.githubusercontent.com/5937600/217811653-005fdc7a-5850-44d7-bdd3-603510fa1eb4.png">

_half-top_

<img width="116" alt="image" src="https://user-images.githubusercontent.com/5937600/217811852-9843b53d-3561-41b5-97de-02981c1430a6.png">

_quarter-top-left_

<img width="193" alt="image" src="https://user-images.githubusercontent.com/5937600/217813026-05bb92a1-570c-4f1f-bb4c-2b9bd7608bd2.png">


the **dotted path** that is shown in your link was actually the most tricky one because it isn't directly supported via params of the component but has to be applied via css styles but I got it working:
<img width="133" alt="image" src="https://user-images.githubusercontent.com/5937600/217809345-800cb181-a9fc-42fd-87a0-498d3149c24a.png">
you can even change the style of the "dots" 
<img width="145" alt="image" src="https://user-images.githubusercontent.com/5937600/217809807-d8f2b2da-6cce-4654-b354-d277866d3a2a.png">

(note that there is a caveat: if you use a border color, also the border becomes dotted)

**line_cap** (butt, round, square, none)

round: 
<img width="118" alt="image" src="https://user-images.githubusercontent.com/5937600/217814847-01f2a170-16ae-44d2-b2cc-affd70eebc74.png">


_editable value_
btw: I also allows you to type the value in the middle (=input field)

If you are happy with the result, I am gonna cleanup the code and do a PR

**Comment by hmerk** [comment]
@stefan-hoehn 
I am absoutely happy with what you have achieved, many thanks !!!!!!!!!!!

**Comment by digitaldan** [comment]
@stefan-hoehn thanks for the updates to the widget, they look great.

 > the dotted path that is shown in your link was actually the most tricky one because it isn't directly supported via params of the component but has to be applied via css styles but I got it working:

Can you share your configuration for this?

**Comment by stefan-hoehn** [comment]
Sure, the docs are here: https://next.openhab.org/docs/ui/components/oh-knob-cell.html#dottedPath
Use the css stroke-dasharray style - unfortunately I noticed due to your question that property is a number at the moment (setting it to 5 for example still shows the effect), so you cannot leverage the full power of the style. Therefore I quickly changed that with this PR:

https://github.com/openhab/openhab-webui/pull/1773
