### ISSUE TITLE
Widget UID is only allowed to contain A-Z,a-z,0-9,_ - but not "-" - every openhab component contains this sign

### ISSUE THREAD

**Issue by ulbi** [openhab/openhab-webui#1906]
## The problem
I've ~ 70 widgets, couple of pages. After upgrading to OH 4.0 Milestone 2.
I had to adjust a couple of widgets and do get the error:
Widget UID is only allowed to contain A-Z,a-z,0-9,_

Cause is a UID like "Light-Item"

As you can see in the screenshot - nearly all UI element names contain this sign "-".
Can we allow this sign once again?

## Expected behavior
Allow the previous signs in the widget UID like in openhab 3

## Steps to reproduce
1. Create a new widget in openhab 3 and set the UID to "Light-Item"
2. Save it
3. Update to openhab 4 Milestone 2
4. Try to edit your widget "Light-Item"
5. Save it
--> you wont be able to do so.

1. 

## Your environment

```yaml

```

## Browser console

```txt

```

**Comment by florian-h05** [comment]
This needs adjustment of the REGEX and the message here:

https://github.com/openhab/openhab-webui/blob/21a30972a89ce8a8595242cd19202a69c68b75a8/bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue#L255-L256

For the REGEX, just add `-` after the `_`.


Would be great if you could open a PR, because then I can review and merge it and don‘t have to wait for review from the other maintainer.

**Comment by ulbi** [comment]
@florian-h05 Sorry, was offline for a couple of days. Thanks to @stefan-hoehn and you to address this.
