### ISSUE TITLE
[mainui] Ability to filter rules by script type

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-webui#1943]
## The problem

I am using a mix of UI based rule types.

When possible, I use simple actions and conditions without script.
Second level use is blockly (with GraalVM), both in script action and script condition.
Most complex rules use pure javascript (GraalVM).
And there are rules left in Python.

Sometimes want to review all rules of one type to adjust things that are specific to the type/language. It would be handy to be able to easily filter the rules for used script type.

## Your suggestion

Enhance the developer sidebar search capability to search in the rule yaml code for matches. This would allow searching for e.g. `application/javascript` or `blockSource` (should be there for Blockly rules).

## Your environment

OH4 Snapshot build 3513

**Comment by florian-h05** [comment]
Searching for a MIME type is already possible, see https://next.openhab.org/docs/tutorial/tips-and-tricks.html#search and the code:
https://github.com/openhab/openhab-webui/blob/46cf0299ab3439a8128254d80c5a55fa2859d7d8/bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue#L476-L515

Instead of allowing to search within the rule YAML (which is not possible, because the rules aren’t stored in YAML and creating the YAML for every rule for the search could be too heavy-weight, but JSON.stringify the object of the rule is a good alternative) or the rule object, I’d rather modify this function in a way that a search for block, or Blockly matches a rules where Blockly is used.

**Comment by mherwege** [comment]
Thanks for the hint. I wasn't aware searching for exact MIME type was supported already. I will create a PR for Blockly.
