### ISSUE TITLE
Cant add colorpicker widget to Group

### ISSUE THREAD

**Issue by proggprod** [openhab/openhab-webui#1965]
## Expected Behavior

I have a group that contains all 'Color' items of my lights. I want to be able to send a color to all items by using a colorpicker widget on the group. But when I choose colorpicker as the default standalone widget, I see nothing

![image](https://github.com/openhab/openhab-core/assets/81530084/de511a1f-7201-40a5-81a7-2b3029e34434)

**Comment by florian-h05** [comment]
You have to set the group type to color and ensure that at least one of the members has a state. If the Item state of the Item for the color picker is no color (e.g. because it is `NULL`), the color picker won't show up.

I however will add an option to the color picker that allows the user to define a default value that will be used in that case.
