### ISSUE TITLE
French translations in Crowdin to be validated for UIs

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#1968]
@ghys : is it you who validates the French translations in Crowdin for this repo ?
That looks really strange, most translations are there in Crowdin but none is validated.
I just added the one missing for Main UI, Basic UI and classic iconset but they will trigger a PR probably only if they are validated by someone.
I don't have the validation rights in Crowdin for UIs.

![image](https://github.com/openhab/openhab-webui/assets/10186704/317270e3-01d3-4d87-8581-a6098db3763e)

**Comment by lolodomo** [comment]
I see we already have two pending Crowdin PRs: #1950 and #1728.
@wborn : any idea why we have several concurrent PRs ?

Can someone please trigger an update in Crowdin for my updated French translations ?

**Comment by wborn** [comment]
> any idea why we have several concurrent PRs ?

It's configured to be like that:

https://github.com/openhab/openhab-webui/blob/main/crowdin.yml
https://github.com/openhab/openhab-webui/blob/main/crowdin-habpanel.yml

**Comment by wborn** [comment]
I see that HABPanel is still has its own Crowdin project so that explains the need for two configs/PRs, see:

* https://crowdin.com/project/openhab-habpanel
* https://crowdin.com/project/openhab-webui

So the translations probably never got merged into the openhab-webui project on Crowdin when the HABPanel code was merged from its [seperate repo](https://github.com/openhab/org.openhab.ui.habpanel) into this repo.

**Comment by lolodomo** [comment]
It looks like my changes finally occurred in the open PR. So either it is automatic or someone pushes a button in Crowdin.

**Comment by lolodomo** [comment]
I merged the PR regarding MainUI, BasicUI, ...

**Comment by lolodomo** [comment]
> I think it was configured at some point to push any change to the strings (even before approval) to the current PR, so the approval is not strictly necessary.

Ok, that is what I noticed.
