### ISSUE TITLE
[Blockly] "datetime from item" block throws error when used

### ISSUE THREAD

**Issue by zolakk** [openhab/openhab-webui#2097]
## The problem
I have a blockly rule that uses the "datetime from item" block and when it executes it throws this error:
`Script execution of rule with UID 'ruleUID' failed: org.graalvm.polyglot.PolyglotException: Error: "MyItem (Type=DateTimeItem, State=UNDEF, Label=Next Timer, Category=, Tags=[Point], Groups=[MyItemGroup])" is an unsupported type for conversion to time.ZonedDateTime`

## Expected behavior

Return a valid result

## Steps to reproduce

1.  Create a blockly rule that uses the "datetime from item" block

## Your environment

openHAB 4.0.3
Release Build
Docker container on Ubuntu

## Additional information
Issue appears to be because the block generates this code:
`time.toZDT(items.getItem('MyItem'))`

instead of this code:
`time.toZDT(items.getItem('MyItem').getState)`

**Comment by rkoshak** [comment]
> State=UNDEF

That's your problem. The Item doesn't have a DateTimeType as it's state. Either this Item hasn't been initialized or what ever Thing/Channel it's linked to is having trouble and is updating the Item to `UNDEF`. `UNDEF` cannot be converted to a ZonedDateTime, hence the error.

**Comment by zolakk** [comment]
Then why does it work when I take the exact same java code it generates and paste it into a rule with the .getState added and no changes to the item?

**Comment by rkoshak** [comment]
But what's it supposed to do if the Item is UNDEF besides generating an error? 

I misread the error. I thought the problem was because the Item's state was UNDEF.

But what you are running into is a known bug in the underlying openhab-js library which has already been fixed. `time.toZDT()` was failing to recognize when it was passed an Item and it tried to parse it as a String and obviously fails. 

You need to update openhab-js to the latest release or update OH to at least 4.1 M1 to get the fix.

**Comment by zolakk** [comment]
Ah ok, I'll go ahead and do that. Since this is already then fixed in the latest release i'll close this out. Thanks.
