### ISSUE TITLE
[MainUI] Closing Location/Equipment/Properties does load a wrong page in Milestone 4.1.0.M4

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-webui#2196]
Best is to share a recorded video: [https://drive.google.com/file/d/1p1DLw-PepDrYO34Kv9jeFX-wSX94riyO/view?usp=sharing](https://drive.google.com/file/d/1p1DLw-PepDrYO34Kv9jeFX-wSX94riyO/view?usp=sharing)

This only happens in 4.1.x Milestones (I have seen in 4.1.0.M3 and 4.1.0.M4). No issues in openHAB 4.0.4. 
It always jumps back to the previous page that was loaded. Same in Location, Equipment or Properties-Tab.

Tested in Chrome and Edge with same result.

**Comment by kristofejro** [comment]
I can confirm it happens also on my openHAB 4.1.0.M4.

**Comment by lolodomo** [comment]
This bug is very annoying.
@florian-h05 @kaikreuzer : I can't imagine we can release 4.1 with such a bug.

**Comment by florian-h05** [comment]
@lolodomo: I have created a PR to fix that.

**Comment by ghys** [comment]
Yes in fact there's a bug that occasionally occurred even before (I think many have experienced a "double-back" when going back), this is likely a bug in Framework7's router actually.
I think it is related and makes the router issue even more prominent.
#2211 will likely alleviate the problem but not solve the actual root cause, which I really want to solve "one day".

**Comment by florian-h05** [comment]
Probably the bug in f7router has already been fixed, but our deps are really outdated ... luckily #2151 may help with that.
