### ISSUE TITLE
Initial setup : no more possible to  select add-ons to be installed with OH 4.1M4

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2197]
With 4.1M4, it is no more possible in the initial setup to select add-ons to install. Nothing happens when clicking on "Sélectionnez les modules à installer" et no list is presented.
![image](https://github.com/openhab/openhab-webui/assets/10186704/ebaff744-c4b5-4c28-afa8-cb33d906aab4)

**Comment by mherwege** [comment]
This is caused by an early merge of https://github.com/openhab/openhab-webui/pull/2150.
The `/rest/addons/suggestions` is not available yet in core, resulting to a failure creating the addon list.
It should be OK when https://github.com/openhab/openhab-core/pull/3806 gets merged. If not, the PR should be reversed.

**Comment by lolodomo** [comment]
It is solved in snapshot 3760.
