### ISSUE TITLE
Custom widgets no take full space

### ISSUE THREAD

**Issue by sifourquier** [openhab/openhab-webui#230]
Hi
Is possible to change .template-contents.margin:auto to margin:0 ?
that do a realy best result when you use iframe

With auto
![auto](https://user-images.githubusercontent.com/7439896/79673355-527c8500-81d9-11ea-8f4e-5cee71534506.png)

With 0
![zero](https://user-images.githubusercontent.com/7439896/79673361-5c05ed00-81d9-11ea-94bb-2c87bba061a1.png)

you can test with a custom widget with 
<div height="100%" class="frame-container ng-scope" ng-if="!vm.widget.nosuffix">
  <iframe width="100%" height="100%" name="New Widget" ng-style="{ 'background-color': vm.widget.background }" frameborder="0" ng-src="https://www.openhab.org/" src="https://www.openhab.org/"> </iframe>
</div>

**Comment by ghys** [comment]
You have this option to bypass the template-content wrapper altogether:

![image](https://user-images.githubusercontent.com/2004147/79687253-47ac0980-8246-11ea-8434-012a1a7fc3e8.png)

Probably not a good idea to make changes like that now for everyone since it might break other people's stuff, you can do it for yourself in a custom CSS file (you have an option to add a custom CSS in the settings).

**Comment by sifourquier** [comment]
Thanks you i have try this option but i think I had other issus in my code.
Now that work fine :)
Je continue avec mon mauvais Anglais pour les autres ;)
