### ISSUE TITLE
BasicUI sitemap elements with valuecolor=["white"] are wrongly rendered in black

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#2570]
In BasicUI Sitemap if an element has the `valuecolor=["white"]` attribute it is wrongly rendered in black.

By contrast the `valuecolor=["#ffffff"]` and `valuecolor=["red"]` do work fully as expected.

```
Frame label="Living Room Media System" {
    // "#ffffff" => OK
    Switch item=AV_System_Scene_Control label="" icon="24gswitch" mappings=[PowerOff="Off", Music="Music", Bluray="Bluray", Tv="Tv"] valuecolor=["#ffffff"]
    // "white" => NOT OK!!
    Switch item=AV_System_Scene_Control label="" icon="24gswitch" mappings=[PowerOff="Off", Music="Music", Bluray="Bluray", Tv="Tv"] valuecolor=["white"]
    // "red" => OK
    Switch item=AV_System_Scene_Control label="" icon="24gswitch" mappings=[PowerOff="Off", Music="Music", Bluray="Bluray", Tv="Tv"] valuecolor=["red"]
}
```

**Comment by lolodomo** [comment]
This is due to the enhancement #2521.
You can disable this behaviour, there is a new option for that.
![image](https://github.com/openhab/openhab-webui/assets/10186704/1a360ae8-7da7-4352-8d30-09acf8098dfa)


PS: I was sure there will be users that don't like this behaviour and I added an option for that.
