### ISSUE TITLE
[Main UI] Icon Expressions usage

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#268]
I am trying to play around with changing the icon color using expressions in a plan marker:

![image](https://user-images.githubusercontent.com/1903737/83340160-b8a10100-a289-11ea-8306-ef2155ca3cf7.png)

But i'm not sure what's in "scope" to access here.  I'm guessing its the inherited properties from the widget-mixin class, but i'm not sure how to access the item configured in the marker.  I am trying to do something like:

```js
=(+items[props.item].state > 0 || items[props.item].state === 'ON') ? 'yellow' : 'black'"
```

But it seems as if `items` is empty and i can not access the `props `or `config` objects  from here?  This is a slight adaption from your custom gauge widget @ghys .

The other thing is i'm not quite sure i understand is:  how does Vue "eval" this string on its icon color binding?  

For example, the binding code here evaluates `config.iconColor`, which is a variable, but i don't understand why it then evaluates the content of that variable ( so its effectively evaluating twice), but of course it is doing this.  Right now this seems like vue-doo  to me :-) 

```js
 <f7-icon v-else-if="config.icon" :color="config.iconColor" :size="config.iconSize || 40" :ios="config.icon" :md="config.icon" :aurora="config.icon"  />
```
 I'm also not familiar with prepending the evaluation string with a `=`  in the first example ? 

Thanks!

**Comment by ghys** [comment]
The expressions are not evaluated by Vue but with https://www.npmjs.com/package/expression-eval
here:
https://github.com/openhab/openhab-webui/blob/b0bdefe5b5dc2d7068f58fd93413ef4ced6ce973/bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js#L29-L50
It will explicitely expect a `=` to distinguish expressions from literals, it's a convention to mimic Excel-like expressions like `=SUM(A1:A3)` you can put in spreadsheets, and the context (objects you can use) is currently very limited:
- `items` to access states and displayStates only, not the entire item object;
- `props` (only defined in the context of custom widgets, those are the configured values of the properties _you_ defined for your custom widget);
- the `Math` & `JSON` objects (useful for rounding values or to examine objects);
- and some info about the current theme and device - `theme`, `themeOptions`, `device`.

You cannot access other config parameters in an expression, as the risk of provoking an infinite recursion/stack overflow is high.

`items` is initially empty because it's not a regular map, it's a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) managed by a Vuex store which will start tracking the state of an item when accessed by name as a property.
See: https://github.com/openhab/openhab-webui/blob/master/bundles/org.openhab.ui/web/src/js/store/modules/states.js

So if you're in the context of a regular floorplan marker, the only way to use it is to explicitely specify the item name like:
```
=(+items.MyItem1.state > 0 || items.Myitem1.state === 'ON') ? 'yellow' : 'black'"
```
(or `items['MyItem1'].state` which is equivalent).

**Comment by digitaldan** [comment]
>The expressions are not evaluated by Vue but with https://www.npmjs.com/package/expression-eval

>items is initially empty because it's not a regular map, it's a Proxy managed by a Vuex store

Well I'm glad i asked :-)  That would have taken me a while to figure out, but totally makes sense,   thanks.  

So really, any of the properties of the widget can use expressions then, for instance the icon itself could return a different value like:
```js
=(items.MyItem1.state == 'COOL') ? 'f7: thermometer_snowflake' : 'f7: thermometer'
```

Lots of possibilities .... and  I could see having an expression code dialog box at some point to help with the syntax.
