### ISSUE TITLE
Thing handleConfigurationUpdate issue

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#2704]
Hi I'm working on a binding that i was hoping to take advantage of the `handleConfigurationUpdate` method to be able intercept configuration updates.   

However, in my testing, when i click "save" on a thing in the UI, the order of operations is `dispose() -> initialize() -> handleConfigurationUpdate()` .   I also tested this against the z-wave binding, which has similar functionality about intercepting updates, and its also behaving the same.

My understanding is that if this method is overridden, then any updates to the config should not trigger a `dispose() -> initialize()` on a thing and instead the `handleConfigurationUpdate()` override would be responsible for that if needed.  Looking at the core code, it seems `handleConfigurationUpdate()` handles the thing lifecycle after an update  if not overridden. 

Am i misunderstanding how this is suppose to work ? 

I'm on OH 4.3 nightlies right now, but i'm pretty sure this behavior is also in the 4.2  release.

**Comment by digitaldan** [comment]
Thanks @J-N-K !

**Comment by digitaldan** [comment]
So looking at this a bit more, if i add some logging, when changing just a simple thing config value, save is called twice with:

`configDirty=true, thingDirty=true, saveThing=undefined` which updates the whole thing
and then
`configDirty=true, thingDirty=false, saveThing=undefined` which is suppose to update just the config

I would think save is only suppose to be called once, and should only be updating just the config, not the whole thing.   Right now the save method is recursively calling itself again at line 538 (hence saving twice), i'm trying to make sense of the logic here, but its quite confusing. 

https://github.com/openhab/openhab-webui/blob/6139039f6c1d1fcda63a578a7cbb7cf6deed3a74/bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue#L517-L540

**Comment by ghys** [comment]
I'll admit it's kind of a mess.
You can trace that back to #287 which was supposed to solve #283.

Basically you can't rely on `/rest/thing/:thingId` alone when you have configuration to update (even if you pass it your configuration in the request body - that was the point of #283 as well). You have to use the `/config` endpoint.
The problem is that when you save the thing in the UI you want potentially do both (i.e. update the label for instance, and any configuration you changed, if you have made changes in both those areas), that's why it may call both endpoints if it thinks both the thing itself and its config has changed...

Then there was https://github.com/openhab/openhab-webui/commit/4d82cd64db60421288ca68bdc5a67ec38387eae7#diff-82a2bcdda41989ee81ed1f512cebeea5bccfc5fdaf337c812a5d0eed5d3d44d0 which introduced the `"DirtyMixin"` and introduced a bunch of changes as well.

> when changing just a simple thing config value, save is called twice with:
`configDirty=true, thingDirty=true, saveThing=undefined`

So in that case thingDirty I believe *in theory* should be false.
I'm not sure but I suspect it was decided during #887 it wouldn't hurt to consider the whole thing dirty if only the config was dirty, that way you would have the confirmation dialog if only the config was changed. But you would have a PUT `/rest/things/:thingId` even if the thing itself wasn't changed.

There was also https://github.com/openhab/openhab-webui/commit/866d9e559e7b4736b39f284a5d94376089cfd14a#diff-82a2bcdda41989ee81ed1f512cebeea5bccfc5fdaf337c812a5d0eed5d3d44d0 later.

**Comment by digitaldan** [comment]
I have a fix, was actually surprisingly easy to fix once you pointed out the changes @ghys , thanks!

**Comment by ghys** [comment]
I do have to say though, I still to this day do not understand why there have to be two endpoints to save a thing.
The main `PUT rest/things/:thingId` one, should be an "atomic" operation, so that the UI code doesn't have to jump through hoops, and the code in that handler should handle configuration updates similarly to the `/config` one as the configuration is part of the request's body.
