### ISSUE TITLE
[BasicUI] Text input element

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-webui#274]
There currently is no easy way to have a text input field in a BasicUI sitemap.

This would be useful wherever an items needs a free text input. For instance, I am working on developing a universal [UPnP AV control point binding](https://github.com/mherwege/openhab-addons/tree/upnp/bundles/org.openhab.binding.upnpcontrol). It allows searching the content directory on a media server with the search criteria as an input. An example of an input string would be: `dc:creator contains "SpringSteen"`.

There is a [workaround](https://community.openhab.org/t/input-field-for-number-free-text-for-openhab-uis/12461/6) for this using a Webview, but the layout is never fully consistent in that case.

**Comment by openhab-5iver** [comment]
A text input widiget seems like something to consider for the new UI (#266).

**Comment by DerOetzi** [comment]
I think there should be more specialized types of input fields beside text as well. For example date input or time input or password. And I don't agree to you @openhab-5iver that this should be only a widget for new UI but although for sitemap-driven existing UIs, as they are wide spreadend for example for using "same" UI in webbrowser (BasicUI) and on smartphone (android-app). And personally I'm hoping I can use my sitemap, which is about 4500 lines long, in long-term at OH3 as well, because in my opinion you can do really intuitive not overloaded UIs for users with a simple UX.

**Comment by ghys** [comment]
> A text input widiget seems like something to consider for the new UI

Noted, will keep that in mind. 

Discussions about the evolution of the sitemap model should be discussed in openhab-core, where it's defined - not here.
