### ISSUE TITLE
[MainUI] New sitemaps do not understand "visibility" & "valuecolor"

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-webui#324]
When trying to import my legacy sitemap using the New UI's sitemap editor, the lexer is choking on parsing the "valuecolor" attribute

```
Unexpected identifier token: "valuecolor". Instead, I was expecting to see one of the following:
```

An example sitemap entry using value color:
```
Text item=F2_Bedroom valuecolor=[==OFF="GRAY",!=OFF="green"]
Text label="Security [%s]" item=AlarmMode valuecolor=[==0="green", !=0="red"] icon="dd_security"
```

**Comment by ghys** [comment]
Visibility & color rules are not supported yet in "managed" sitemaps :( So they were left out of the grammar as well.

https://github.com/openhab/openhab-core/blob/ab8aa9ed3af42eeccfd091c4a7085b57c4ac9945/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java#L270

**Comment by stritti** [comment]
I have the same issue transfere my sitemap from 2.5 to 3.0: 
https://github.com/smart-swimmingpool/openhab-config/blob/master/sitemaps/pool.sitemap

**Comment by sirupflex** [comment]
The lack of support for visibility & valuecolor is quite painful and, in my opinion, contradicts a basic rule with OpenHAB. The basic rule is "either do everything in the UI or in text files", otherwise things get very messy and unpredictable with OpenHAB. With the lack of support for these important tags, you force people to maintain existing sitemaps in text files while pages are created in the UI, with no direct visibility of each other.

Please consider the implementation with high priority. In addition, I highly recommend the "visibility" feature to be implemented also for pages in general. If you want to have a user-friendly page that only displays relevant info based on a current status, you do need this feature. Today, you need to list a lot of items on a page but many of them might e.g. be displayed as "UNDEF" and therefore not adding any value to the page, confusing non-geek family members. Please think user-focused here, not technology-focused! OpenHAB 3 has fantastic potential, let's not forget the most important part, i.e. the interface to "general users", i.e. "the rest of the family", otherwise OpenHAB will remain an "IT geek tool". Thank you very much!

**Comment by ghys** [comment]
> In addition, I highly recommend the "visibility" feature to be implemented also for pages in general.

https://www.openhab.org/docs/ui/building-pages.html#widgets-definition-usage

(also: https://twitter.com/youyuxi/status/1378409318102470663)

**Comment by airbone42** [comment]
+1 for this

**Comment by westward** [comment]
+1

**Comment by MUDO86** [comment]
+1
