### ISSUE TITLE
Settings in cfg file for Basic UI are ignored

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#33]
With the recent snapshots (1544 and 1549), it looks like the settings for Basic UI I am setting in a file basicui.cfg are ignored.
Here is the content of my basicui.cfg file:
```
org.eclipse.smarthome.basicui:iconType=png
org.eclipse.smarthome.basicui:defaultSitemap=maison
```
This problem was I think already mentioned by @kaikreuzer on the forum.

**Comment by lolodomo** [comment]
Note that it is still working for Classic UI.

**Comment by lolodomo** [comment]
This is due to the change of configurationPid in WebAppServlet.
Why changing it in Basic UI and not in Classic UI ?
As a breaking change, it should be mentioned somewhere for the user.

**Comment by lolodomo** [comment]
Kai, I think you are the one who changed that ;)

**Comment by kaikreuzer** [comment]
Hm, did I? I guess this must have happened by some huge search&replace operation...

But yes, I nonetheless think it is correct to change it - so it should also be done for Classic UI (and Paper UI?).

And yes, we should add it to the release notes. But I also wonder if we can easily introduce some "migration" script (maybe being called automatically in the update process) that automatically changes such configuration values (instead of `org.eclipse.smarthome.basicui:iconType=png`, it would now simply be `org.eclipse.smarthome.basicui:iconType=png` (as `org.openhab` is automatically prefixed)). @wborn & @BClark09, what do you think about such a migration script?

**Comment by lolodomo** [comment]
In your message, the current value and the new value are identical...

As these settings are defined by the user in the conf folder which is considered as read only by the OH system, such a migration should first require a user acknowledgement.

**Comment by BClark09** [comment]
> what do you think about such a migration script?

As @lolodomo mentioned, the `conf` folder shouldn't usually be changed by the system during a upgrade right? But find an replacements should certainly be doable if we have a list of classes and what they've changed to.

**Comment by lolodomo** [comment]
Was this change finally mentioned somewhere for users who will upgrade to 2.5 ?

**Comment by wborn** [comment]
Not yet. We can add it to the release notes:

https://github.com/openhab/openhab-distro/wiki/openHAB-2.5-Release-Notes---DRAFT

Though I'm on a phone right now. ;-)

**Comment by openhab-5iver** [comment]
Is it too late to get this into the update script?

**Comment by lolodomo** [comment]
I close this issue. If nothing was done, it is now too late.
