### ISSUE TITLE
[MainUI] Show disabled state in Things list

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-webui#342]
In the Things list page, it will show the thing state as `UNINITIALIZED` if the thing is disabled - IMHO it should show that it's been disabled.

![image](https://user-images.githubusercontent.com/1041475/93690635-b382ee80-fad2-11ea-9789-57998d5a1fb9.png)

 If you go to the thing detail page, it then shows the status is `UNINITIALIZED`, and underneath is `Disabled` with the orange "pause" icon - this feel ok, but IMHO could be improved as well - if the Thing is disabled, then IMHO this should be the main state - the fact that it's uninitialized is always going to be the case if it's disabled.

![image](https://user-images.githubusercontent.com/1041475/93690644-cbf30900-fad2-11ea-8e0b-e62e7d4416c7.png)

My suggestion.

* In the things list page, the state should be `DISABLED` rather than `UNINITIALIZED` to make it clear that this is manually disabled, rather than some sort of error.
* In the thing detail page, it is a bit clearer, but I still think the state could be more obviously disabled rather than uninitialised - eg remove the UNITIALISED and make it DISABLED? (I'm less worried about this one).

**Comment by kaikreuzer** [comment]
I agree - that's also how Paper UI handles it.
Although it isn't nice to have an exceptional treatment of Thing statuses by the UI, it is in this case imho very valuable for the UX.

**Comment by ghys** [comment]
Let's try to come up with some sort of general logic then.
Looking at this list of statuses and status details:
https://www.openhab.org/docs/concepts/things.html#status-details
I'd try putting the status detail (second column) in the colored chip
unless it's NONE, in that case use the main status (first column). The
color is still determined by the main status only (green for ONLINE, red
otherwise, or maybe some gray for disabled as an exception). Some status
details are rather long though so they could be a little too big on narrow
screens.

**Comment by kaikreuzer** [comment]
Another suggestion:
Use status for color (UNINITIALIZED = grey, INITIALIZING+UNKNOWN = yellow, ONLINE = green, OFFLINE = red, REMOVING+REMOVED = blue) and a human-friendly label of the status detail as text - with the exception of NONE, where the status should be used as text.

I.e. we would have "ONLINE" and "CONFIG PENDING" in green, "UNINITIALIZED", "DISABLED" and "HANDLER INIT ERROR" in grey, etc.
