### ISSUE TITLE
[Layout Editor] Multi selection of items is offered but does not work as expected

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-webui#345]
In the layout editor I have selected the option "Add from model" in a "Block":
![image](https://user-images.githubusercontent.com/616792/93819890-a09c2580-fc5c-11ea-9599-092327a0122b.png)

In the displayed list I have selected three items:
![image](https://user-images.githubusercontent.com/616792/93819943-b27dc880-fc5c-11ea-8533-cb789312bd38.png)

But only the first selected item is added after I click on "Add 3".

If I use "Add Masonery" instead of "Add Block" it works correctly. If items are selected in the context of a "Block" I think only single selection makes sense.

**Comment by ghys** [comment]
You're right, if you add multiple widgets to a block column, you'll only see the first one - but it's only an arbitrary limitation to avoid confusion rather than a technical one. If you edit the YAML you'll see that the widgets are there, the implementation of the oh-grid-col component only displays one.
I'm considering allowing multiple widgets per column actually, but if it doesn't end up being the case the dialog should only either:
- allow to pick a single item
- add an oh-list-card to the column containing list items representing the picked items.
