### ISSUE TITLE
Options is not working for selection of values during configuration of things

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-webui#357]
The Insteon binding uses options which allows the user to enter their own value or pick from a list of values:

```
<parameter name="productKey" type="text" required="true">
  <label>Product Key</label>
  <description>Insteon binding product key that is used to identify the model of the device.</description>
    <options>
      <option value="F00.00.01">2477D SwitchLinc Dimmer - F00.00.01</option>
      ...
      <option value="X00.00.03">X10 motion Generic X10 motion sensor - X00.00.03</option>
    </options>
  <limitToOptions>false</limitToOptions>
</parameter>
```

With the OH2 paper ui, when creating a new thing the screen initially looks like:

![image](https://user-images.githubusercontent.com/838221/94365056-81096080-0093-11eb-8971-cf30d08834a8.png)

Clicking on the field give you a drop down which you can scroll through, or the ability to type in  value:

![image](https://user-images.githubusercontent.com/838221/94365095-c62d9280-0093-11eb-9a41-7bbc450a496d.png)

The OH 3 UI only gives you the chance to enter a value, and is missing the list of options:

![image](https://user-images.githubusercontent.com/838221/94365137-17d61d00-0094-11eb-9414-de0ca0b676df.png)

**Comment by ghys** [comment]
That's one of those few cases of parameters with options and `limitToOptions=false`, which didn't get much love because I didn't encounter many of them.
#359 improves it a bit although it's still not perfect.

**Comment by rogierhofboer** [comment]
Please reopen this issue, because options are not taken in to account for Number configuration parameters which also have options outside of the range. 

The range is set as min and max of the f7-list-input control, but this way option values outside of this range are not accepted. 

Unfortunately the built-in validation of the f7-list-input control cannot be used in this case and a custom validation should be made to check the range and allow all options (even when outside of the range).
