### ISSUE TITLE
[MainUI] Some suggestions for admin pages

### ISSUE THREAD

**Issue by bobadair** [openhab/openhab-webui#365]
I recently started using 3.0 for development, and I’m really impressed with how much nicer the UI is already! However, I do have a few suggestions for minor improvements. I’m no UI design expert, so take these for whatever they’re worth.

First, in the Thing Config page where configuration options are set, it is nice that parameters that have “password” context set are masked so you can’t see the values. However, it would be even better if there were a way to show the values on demand. I’ve noticed that a lot of newer UIs give the user this option by placing a little eye icon off to the right of the password field which unmasks it when clicked.

Second, on the “Link Channel to Item” page under the “Profile” selection section, why are options for both “No Profile (Default)” and “Default” displayed?  Are they different?

Finally, I think some others have commented on this, but the completion buttons in the header line in the upper right-hand corner of the page (e.g. “Link” on the Link Channel to Item page) keep throwing me off, even now that I know to look for them there. I keep naturally looking to the lower right corner for them. This probably means I'm stuck in my ways. :-) Maybe it would be better to highlight these somehow to make them more noticeable by making them look more like buttons?

**Comment by bobadair** [comment]
Cool!

**Comment by ghys** [comment]
Sorry forgot to answer here:
- the password reveal button was a good idea, it was implemented.
- I renamed "No Profile (Default)" to "(No Profile)" - "Default" is actually the `system:default` profile which is technically, if not functionally, different to no profile at all
- I added big blue buttons, on the _creation_ screens for the desktop theme only, as an experiment. I still prefer buttons in the navbar when editing things because it's consistent with other more complex screens where it's not always an option to put the save button elsewhere. For Android & iOS themes, these are tailored for mobile screens where it's more natural to have these buttons there as well.
