### ISSUE TITLE
[mainUI] Changing semantic class from "Indoor" to "None" does not work

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#443]
To see some locations i trieb to setup a semantoc model og my home and tried to use the limited classes from the model in plemented. In the communisty i read that it is not possible to use the class location and get some location in the location pane. So i changed the clases i used and recognized that if i change the class to None this has some errors.

![image](https://user-images.githubusercontent.com/40339145/97112628-b1b9d580-16e5-11eb-9830-5df1e0793dca.png)

As you in the picture in the tree the zones are still indoor in the right None is selected.

Currently i am on build #1985

**Comment by ghys** [comment]
This actually looks like a problem in core.

Given an item like this:

![image](https://user-images.githubusercontent.com/2004147/97184291-0cfbce80-179f-11eb-959e-8cdd9b7ddd6a.png)

Updating it with a PUT /rest/items/gKitchen with this payload (note how it removes the tag):

![image](https://user-images.githubusercontent.com/2004147/97184448-3583c880-179f-11eb-8a75-909dd0c3b158.png)

Leads to this:

![image](https://user-images.githubusercontent.com/2004147/97184561-59470e80-179f-11eb-86dc-f80ef1dbb6f4.png)

Which is invalid - since the Kitchen tag is not there anymore, the semantics metadata should have disappeared.

@kaikreuzer can you transfer to openhab-core and maybe have a look since you made the semantics metadata provider :)
