### ISSUE TITLE
[mainUI] Follow profile does not have parameters

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#495]
Working on build #2003. The follow profile does not allow to specify which channel to follow. Selecting follow does not change anything.

The expected behaviour is to get a list of channel to select the one/ones to follow.

**Comment by ghys** [comment]
System profiles are defined in core, see https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemFollowProfile.java
Not an UI issue.

**Comment by TBail** [comment]
Could you then tell me how to assign a follow profile to an item using the ui? For offset profile the ui does offer an option.

**Comment by ghys** [comment]
No idea, I have never really used it nor do I really understand how it works 🤷‍♂️ All I know is, it defines no parameters. It's a problem with the profile itself, or at best a documentation issue.

**Comment by ghys** [comment]
I think this profile is meant for those cases where you want for example light2 to "follow" light1 when it changes.
So you link an item to the light1 channel with the default profile, and also to light2 with the follow profile.
So the item will reflect the state of light1 but when receiving a command, it will send it to both light1 and light2.

**Comment by TBail** [comment]
Your description is right. the only thing that is missing is how to enter the follower.

Let me understand this by comparing it to the offset profile. When using the offset profile an small addition textfield open in the ui and it is possible to enter a value. This entry is programmed into the ui. I assume that it is not autogenerated. Is that right?

I checked the java code, but to be honest i am not so deep in java anymore. But what i saw is that SystemFollowProfile is derived from StareProfileType. Maybe this helps.

Otherwise how is the right person to adress this?

**Comment by ghys** [comment]
> I assume that it is not autogenerated. Is that right?

It _is_ autogenerated from the profile description.
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/offsetProfile.xml
The UI autogenerates practically everything when it comes to this stuff.

For the follow profile, the follower is the channel you link to.
``` 
item1 <=> channel1 (default)
item1 <=> channel2 (follow)
```
when you send ON to item1, it will send ON to channel1 and also update item1's state to ON.
because of the follow link to channel2, it will also send ON to channel2.
For these support questions, the best is to ask in the community forum.

**Comment by TBail** [comment]
I will open a thread in the forum ans then lets see what happens.
