### ISSUE TITLE
[CometvisuUI] not working with OH3.0.0 M2

### ISSUE THREAD

**Issue by HazeHunter11** [openhab/openhab-webui#509]
The cometvisu binding is not working with openHAB 3.0.0 M2 docker release. 

**1. The autodownload function is not working, it returns the following error:**
> [etvisu.internal.util.ClientInstaller] - error opening release zip file zip END header not found java.util.zip.ZipException: zip END header not found

**2. When downloading the release manually I retrive 401 (Unauthorized) messages when loading the preview page. I can send Item commands but I can not retrive the item state due to the 401 error.**  
>:8102/rest/config-descriptions/ui:cometvisu:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
> :8102/rest/services/org.openhab.cometvisu/config:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by peuter** [comment]
The 401 errors are from request to the comefvisu binding configuration. They are not needed for a working cometvisu and have nothing to do with the problem that the states cannot be requested. The actual problem is, that the states response is an escaped json string, which would have to be decoded twice to work: `""{\"d\":{\"Licht\":\"OFF\"}}""`. 
I will investigate this when I find the time, but don't expect anything too soon. Usually I need 2-4 weeks to get a working development version of openhab running and can even start to debug the problem. And that is really annoying.

**Comment by peuter** [comment]
Ok the good news is that I managed to get a debug setup running by deleting everything and start from scratch by using the latest documentation. The bad news is: I am not able to reproduce this problem when I run openhab from within the eclipse IDE.

So I need some help by anyone who has an idea what is going on here. I remember that there used to be different osgi runtime environments between the standalone openhab version and the one running in eclipse (karaf vs. equinox?). Is this still the case and is it possible that this is the reason for the differences in the encoding of the SSE response?
