### ISSUE TITLE
[MainUI] Alexa metadata: unable to add Group Endpoint metadata values to group items

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-webui#511]
Hi, I'm trying the Alexa skill with openHAB 3 snapshot version. 
I'm not able to set the correct metadata parameters in items of type "group" like for example "Endpoint.Thermostat" which if I understand everything correctly is required to expose some complex items to Alexa (documented in this section https://www.openhab.org/docs/ecosystem/alexa/#group-endpoint).
I did a quick review of the code and it seems like the ui do not include the Endpoint.* metadata options.
I will say this is a bug but maybe I'm missing something.
Thanks for the help!

**Comment by ghys** [comment]
I'm not keeping current on these metadata namespaces.
When there are changes, the maintainers are encouraged to submit a PR for the UI to follow.

**Comment by mufflastig** [comment]
I stumbled upon the same problem. I did not expect this, since the group endpoints have been around since the release of the Alexa Skill V3 in 2019. Manually changing the alexa value of an equipment to e.g. "Thermostat" via the code tab in the UI works, but afterwards breaks the config tab (it is empty, the value is not even displayed).

Who would be the right person to make these changes? @digitaldan can you help? An easy fix would be to add all endpoints as selectable values but a far better option would be to only enable these for actual group items.

**Comment by ghys** [comment]
Fixed with #767.
