### ISSUE TITLE
Array.prototype.flat doesn't exist on older browsers

### ISSUE THREAD

**Issue by crnjan** [openhab/openhab-webui#647]
Maybe a bit odd issue, but would be great to see OH content on LG TV's build in web browser - overview tab renders fine (at least the content I have in there), but other tabs don't - only `separator` text is rendered, but not the cards.

Seems as LG webOS uses Chromium 68 (http://webostv.developer.lge.com/discover/specifications/web-engine/); tried to download it (tried with Version 89.0.4358.0) and OH loads fine on my MAC ...

Any suggestions would be appreciated.

(EDIT: tested with OH3 Build #2078)

**Comment by crnjan** [comment]
![image,50%](https://user-images.githubusercontent.com/3818211/102334722-4e368080-3f8f-11eb-84a0-3880c8ee39e7.png)

Downloaded an older version and can reproduce the same, no idea why webOS 5 (from 2020!) bundles with such old  Chromium version. Any chance to somehow make this work on webOS 5 (Chromium 68)?

**Comment by ghys** [comment]
![image](https://user-images.githubusercontent.com/2004147/102494496-0427ca80-4075-11eb-96de-bcad958ce9c7.png)
https://stackoverflow.com/a/50993569

By the way: when you opened that issue, I believe it said up front:

`
Please DO NOT ERASE this template, but fill in the details as requested. This will ensure your issue is properly filed and will be considered. Otherwise, we may reserve the right to close it without further action.
`

which you did anyway, and then:

`
Open the developer tools in your browser, go to the Console tab and paste errors and other messages that might be relevant to this issue.
You may also paste a screenshot if you prefer.
`

That would saved me the hassle of doing it for you. So next time, if you can't be bothered to help by following simple instructions, I won't be bothered to help you.

**Comment by crnjan** [comment]
Hey!

Let me first try to explain myself - when I created the issue I only seen it on TV (and no error logs there) + downloaded latest Chromium (falsely under the impression webOS includes an up2date browser) - and also got no errors there - since naturally all worked with latest version. And then I filled the issue and there was nothing to add at that time.

Only later I found out webOS uses Chromioum 68 and was then able to reproduce the issue - but failed to provide all the data, sorry for that.

Greatly appreciate your effort (not just regarding this issue, but overall, really enjoying the new UI btw) and thx for providing feedback.

Based on your post I added 

```
if (!Array.prototype.flat) {
  // eslint-disable-next-line no-extend-native
  Array.prototype.flat = function (depth = 1) {
    return this.reduce(function (flat, toFlatten) {
      return flat.concat((Array.isArray(toFlatten) && (depth > 1)) ? toFlatten.flat(depth - 1) : toFlatten)
    }, [])
  }
}
```

to the top of `bundles/org.openhab.ui/web/src/js/app.js`, created new jar and updated my OH3 - and it works now!!!

Is there any chance to include something like this to codebase? And if yes, where would be a good place to add it?

Thanks again,
 Boris
