### ISSUE TITLE
basicui: rgb color selector css improvements

### ISSUE THREAD

**Issue by ako-3004** [openhab/openhab-webui#934]
## Which UI are you reporting an issue for?

- [ ] Basic UI

## The problem

RGB Color selector dot is not exactly placed, reason is the css styling

## Your suggestion

Change color picker handle css class ".colorpicker__handle" like following:
- remove current margin setting "`margin: -12px 0 -12px;`" which is also wrong (top and bottom are set here, not top and left)
- add "`transform: translate(-50%, -50%);`" what makes the px value irrelevant. works on all modern browsers. 

you instantly see a correct placement exactly in the middle for rgb 100% or on the outer cicle line for a single color 100%

![SharedScreenshot](https://user-images.githubusercontent.com/46303527/109885411-bf2c3100-7c7e-11eb-9daa-cdbbcc686caa.jpg)

support for older browsers which is not realy relevant today, but possible:

```
-moz-transform: translate(-50%, -50%);
-ms-transform: translate(-50%, -50%);
-o-transform: translate(-50%, -50%);
-webkit-transform: translate(-50%, -50%);
transform: translate(-50%, -50%);
```

**Comment by lolodomo** [comment]
I just tested and you're right the selector is apparently not well placed.
I am going to test your proposed changes in Firefox/Chrome/Edge.

**Comment by lolodomo** [comment]
Unfortunately, I see a big bug with the colorpicker. When you use it to select a color near the limit of the circle and then close/reopen the popup, you can see that the selector is no more at the same place, either outside the circle or near the center of the circle. Apparently, the problem is only when you select a color near the border of the circle.
