### ISSUE TITLE
Rules interface incredibly slow with large numbers of text based rules

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-webui#939]
I've seen this issue since moving to the original 3.x snapshots (I'm on S2225 right now).  I thought I created an issue on this a long time back, apparently I didn't.  I have a little under 200 rules on my system, all are text based.  Some of them are very long (thousands of lines).  When I attempt to open the rules page on the UI, CPU on my workstation (specifically the Chrome process) drives way up, as does memory usage.  Even doing basic things like scrolling are almost impossible (it can take up to a minute to process a single scroll action).  Eventually Chrome throws the "this page is stuck do you want to kill it" error.  

When I use the developer tools in Chrome it identifies "Run Microtasks" as what is sucking up all the CPU (which it is saying is tied to js/app.js).   The two paths that seem to be the problem are Qe -> pn -> a -> e._update (using about 70% of the CPU time) and Qe -> pn -> a -> e._render (using about 29% of the CPU time).  

![OH-UI2](https://user-images.githubusercontent.com/53797132/110255045-7bc01400-7f57-11eb-9688-94982ced84d7.JPG)

![OH-UI](https://user-images.githubusercontent.com/53797132/110255007-53d0b080-7f57-11eb-93b6-ba2a4de2cf7e.JPG)

![OH-UI3](https://user-images.githubusercontent.com/53797132/110255217-32bc8f80-7f58-11eb-987d-c6472c3a2f73.JPG)

**Comment by ghys** [comment]
I don't have 200 rules but if I duplicate them by code (in a development instance so not optimized code) to have 308:

![image](https://user-images.githubusercontent.com/2004147/110262055-a9867680-7fb2-11eb-9887-100b2b4f1422.png)

This is a typical perf record that I get:

![image](https://user-images.githubusercontent.com/2004147/110262142-01bd7880-7fb3-11eb-907d-d2fbff99e201.png)

It takes a couple seconds to render (again, with unoptimized code) and then the performance is okay.
You can identify 2 big blocks (frames/tasks) on the record above, that you can relate to network requests:

The first one (XHR Load) is related to the rendering of the initial list - related to `/rest/rules?summary=true`

![image](https://user-images.githubusercontent.com/2004147/110262243-65e03c80-7fb3-11eb-8460-76ded7e4dd8a.png)

The second one is related to `/rest/events?topics=openhab/rules...` and is for updating the statuses when something occurs:

![image](https://user-images.githubusercontent.com/2004147/110262304-932cea80-7fb3-11eb-89ad-7a7341a37ccf.png)

Then since I don't have rules changing statuses all the time the rest is mostly idle.

So my guess is not so much the amount of rules that you have, but the fact that they likely change their statuses very often, meaning receiving a lot of traffic on your SSE endpoint and having to update the status badges, or worse, the whole list. You can check that by going to the Network tab in the dev tools, finding the `/rest/events?topics=openhab/rules...` and going to the EventStream tab.

![image](https://user-images.githubusercontent.com/2004147/110262545-5ca39f80-7fb4-11eb-9758-12928205f1c0.png)

**Comment by morph166955** [comment]
I think you have hit the nail on the head.  I do have a whole bunch of rules that fire pretty frequently on crons or item state changes.  Event stream is definitely seeing a whole bunch of rule fires/idles/etc. every second.  I would say this should be easily recreated by setup a bunch of rules that fire by cron every second.  So the question is, is this fixable?

**Comment by fapgomes** [comment]
Same problem here, did you manage to figure out a solution for this?

**Comment by florian-h05** [comment]
Fixed by #2623, which fixes exactly what is reported here.
