### ISSUE TITLE
show where item is used

### ISSUE THREAD

**Issue by Gifford47** [openhab/openhab-webui#985]
## The problem

if i change the name of an item and i have used it in a text rule or somewhere else, i have to search either in the errorlog or all config files individually (if necessary with script).
It would be very practical if the UI would show me where each item is used after pressing a button.
e.g.
Item1 --- is used in ---> abc.rules, tasmota.items, general-4 (UI/jsondb)
item2 --- is used in ---> floorplan_tabs (page/jsondb), chart_example_calendar (page/jsondb)
and so on ...

at the moment i use a python script which shows me all paths in which file the item can be found (jsondb and manual conf-files)

## Your suggestion

perhaps a new column in the model view, where each item's usage is displayed after clicking on the item.

## Your environment

```yaml

```

**Comment by rkoshak** [comment]
Doing this will be exceptionally difficult in the UI. It would essentially have to pull in *all* the Items, *all* the Links, *all* the pages, *all* the metadata, and *all* the rules and then for each Item search through all of them and further parse the resultant JSON to get the ID of what ever the Item is found in. Given how long it takes to just load the Items I've no doubt that doing something like this in the UI would lead to completely unacceptable load times if always shown in the model. Maybe it wouldn't be so bad if it were a Developer Tool where you can search for a single Item at a time but even there it will take a great deal of time to pull in all that JSON into the browser, parse through it and do the REGEX search required to find the Item by name.

And that *will not* show you which text config file the Item appears in. There is no information about where the Link, Rule, etc. comes from through the REST API so even after all that work, it'll only be a partial solution.

**Comment by Gifford47** [comment]
thanks for the answer!
but how about running a python script on the server and send the appropriate JSON to the ui? is that technically possible at this time? the python script could then distinguish between text based files and jsondb

**Comment by rkoshak** [comment]
No. One does not "send" stuff to the UI. The UI requests stuff from the REST API and subscribes to an SSE feed from the event bus. So a new REST API endpoint along with a bunch of additions to openHAB core would have to be added to enable anything like this. 

And knowing that an Item exists in one of the JSONDB files is almost useless. For example, knowing Item "Foo" appears in automation.json will tell you that the Item is used in *a* rule that is defined via the UI. It won't tell you *which* rule it's used in. It's almost useless information. Knowing that "Foo" appears in org.openhab.core.item.Metadata.json tells you that the Item has at least one Metadata entry. It doesn't tell you what the entry is nor does it tell you how many entries there are.

Personally I'm of the opinion (and my opinion doesn't count for much) that if you want to see where an Item is used in a text config, you can use grep (or a Python script) like has always been the case since the beginning. For the JSONDB stuff, in order to be remotely useful compared to the effort required to implement it, it'll need to tell you in exactly which records the Item appears. And to achieve that in anything close to efficiently it will require new REST API endpoints and the code behind those to make it happen.

**Comment by Gifford47** [comment]
I have written a Python3 script that searches for items, things or other objects in the conf files or in the jsondb. 
[https://github.com/Gifford47/OH_find_objects](url)
you could rewrite the output of the script as json format and pass it to the web-ui.
would that be a solution?
